### ISSUE TITLE
N not working

### ISSUE THREAD

**Issue by carlitux** [Strider-CD/strider-docker-runner#38]
\# Creating docker container from strider/strider-docker-slave docker
$ n stable node
Error: spawn ENOENTexecvp(): No such file or directory

**Comment by davemackintosh** [comment]
This smells like an odd permissions problem to me :boom:

Can you give us some more information on the issue/error please.

**Comment by carlitux** [comment]
Permissions for what? I think n was installed by strider, docker runs under
root (what I read). Please let me know what do you need.

**Comment by carlitux** [comment]
n is working well with default runner, but on docker getting that error... any idea? any way to debug?

**Comment by xdissent** [comment]
That's because the `strider-docker-slave` image doesn't install `n`. We're using a custom slave image that *does* install `n` and everything is working as expected. Should prob file an issue there (https://github.com/Strider-CD/strider-docker-slave) to get it added. Our custom build diverges quite a bit from the base image or I would have already submitted a PR. =/

**Comment by carlitux** [comment]
@xdissent I though that I just created the image https://hub.docker.com/r/lcruzc/strider-docker-slave-node/
